-- ============================================================
-- COBOL BANKING SYSTEM - DATABASE SCHEMA CREATION
-- Database: DB2
-- Schema: COBOL
-- Description: Core banking system tables for demo
-- ============================================================

-- Create schema if not exists
CREATE SCHEMA IF NOT EXISTS COBOL;

-- Set current schema
SET SCHEMA COBOL;

-- ============================================================
-- CUSTOMER TABLE
-- ============================================================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(5),
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30) NOT NULL,
    FULL_NAME VARCHAR(100),
    DATE_OF_BIRTH DATE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    MARITAL_STATUS CHAR(1) CHECK (MARITAL_STATUS IN ('S', 'M', 'D', 'W')),
    NATIONALITY VARCHAR(3),
    ID_TYPE VARCHAR(3),
    ID_NUMBER VARCHAR(20),
    ID_EXPIRY DATE,
    ADDRESS_LINE1 VARCHAR(50),
    ADDRESS_LINE2 VARCHAR(50),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    POSTAL_CODE VARCHAR(10),
    COUNTRY VARCHAR(3),
    HOME_PHONE VARCHAR(20),
    MOBILE_PHONE VARCHAR(20),
    EMAIL VARCHAR(60),
    EMPLOYER_NAME VARCHAR(50),
    OCCUPATION VARCHAR(30),
    ANNUAL_INCOME DECIMAL(15,2),
    EMPLOYMENT_STATUS CHAR(1) CHECK (EMPLOYMENT_STATUS IN ('E', 'S', 'U', 'R')),
    CUSTOMER_SEGMENT VARCHAR(3) CHECK (CUSTOMER_SEGMENT IN ('RET', 'PRI', 'WLT')),
    RELATIONSHIP_MANAGER VARCHAR(8),
    CUSTOMER_SINCE DATE,
    CUSTOMER_STATUS CHAR(1) CHECK (CUSTOMER_STATUS IN ('A', 'I', 'B')),
    RISK_RATING VARCHAR(2),
    CREDIT_SCORE INTEGER,
    KYC_STATUS CHAR(1) CHECK (KYC_STATUS IN ('C', 'P', 'E')),
    KYC_DATE DATE,
    LAST_REVIEW_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- ACCOUNT TABLE
-- ============================================================
CREATE TABLE ACCOUNT (
    ACCOUNT_NUMBER BIGINT NOT NULL PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR(2) CHECK (ACCOUNT_TYPE IN ('SA', 'CA', 'FD', 'LA')),
    ACCOUNT_STATUS CHAR(1) CHECK (ACCOUNT_STATUS IN ('A', 'D', 'C', 'F')),
    CUSTOMER_ID BIGINT NOT NULL,
    BRANCH_CODE INTEGER,
    CURRENCY_CODE VARCHAR(3),
    ACCOUNT_BALANCE DECIMAL(15,2) DEFAULT 0.00,
    AVAILABLE_BALANCE DECIMAL(15,2) DEFAULT 0.00,
    HOLD_AMOUNT DECIMAL(15,2) DEFAULT 0.00,
    OVERDRAFT_LIMIT DECIMAL(13,2) DEFAULT 0.00,
    INTEREST_RATE DECIMAL(6,4),
    LAST_INTEREST_DATE DATE,
    ACCOUNT_OPEN_DATE DATE,
    ACCOUNT_CLOSE_DATE DATE,
    LAST_TRANSACTION_DATE DATE,
    LAST_TRANSACTION_TIME TIME,
    LAST_STATEMENT_DATE DATE,
    MINIMUM_BALANCE DECIMAL(13,2),
    ACCRUED_INTEREST DECIMAL(13,2) DEFAULT 0.00,
    YTD_INTEREST DECIMAL(13,2) DEFAULT 0.00,
    MONTHLY_FEE DECIMAL(9,2),
    LAST_FEE_DATE DATE,
    ACCOUNT_OFFICER_ID VARCHAR(8),
    RISK_RATING VARCHAR(2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- ============================================================
-- TRANSACTION TABLE
-- ============================================================
CREATE TABLE TRANSACTION (
    TRANSACTION_ID BIGINT NOT NULL PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(3) CHECK (TRANSACTION_TYPE IN ('DEP', 'WDL', 'TRF', 'FEE', 'INT', 'LDB', 'LPY')),
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TIME TIME NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALUE_DATE DATE,
    TRANSACTION_AMOUNT DECIMAL(15,2) NOT NULL,
    TRANSACTION_CURRENCY VARCHAR(3),
    EXCHANGE_RATE DECIMAL(11,6) DEFAULT 1.000000,
    LOCAL_AMOUNT DECIMAL(15,2),
    FROM_ACCOUNT BIGINT,
    TO_ACCOUNT BIGINT,
    FROM_BALANCE_BEFORE DECIMAL(15,2),
    FROM_BALANCE_AFTER DECIMAL(15,2),
    TO_BALANCE_BEFORE DECIMAL(15,2),
    TO_BALANCE_AFTER DECIMAL(15,2),
    TRANSACTION_STATUS CHAR(1) CHECK (TRANSACTION_STATUS IN ('P', 'C', 'F', 'R')),
    TRANSACTION_CHANNEL VARCHAR(3) CHECK (TRANSACTION_CHANNEL IN ('BRN', 'ATM', 'ONL', 'MOB', 'BAT')),
    BRANCH_CODE INTEGER,
    TERMINAL_ID VARCHAR(10),
    USER_ID VARCHAR(8),
    AUTH_CODE VARCHAR(12),
    REFERENCE_NUMBER VARCHAR(20),
    DESCRIPTION VARCHAR(100),
    REMARKS VARCHAR(200),
    POSTED_FLAG CHAR(1) CHECK (POSTED_FLAG IN ('Y', 'N')),
    POSTED_DATE DATE,
    POSTED_TIME TIME,
    REVERSAL_FLAG CHAR(1),
    ORIGINAL_TRANSACTION_ID BIGINT,
    ERROR_CODE VARCHAR(4),
    ERROR_MESSAGE VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- LOAN TABLE
-- ============================================================
CREATE TABLE LOAN (
    LOAN_NUMBER BIGINT NOT NULL PRIMARY KEY,
    LOAN_TYPE VARCHAR(3) CHECK (LOAN_TYPE IN ('PER', 'HOM', 'AUT', 'BUS', 'CRD')),
    CUSTOMER_ID BIGINT NOT NULL,
    LOAN_ACCOUNT BIGINT,
    DISBURSEMENT_ACCOUNT BIGINT,
    LOAN_STATUS CHAR(1) CHECK (LOAN_STATUS IN ('A', 'C', 'D', 'W')),
    LOAN_CURRENCY VARCHAR(3),
    ORIGINAL_AMOUNT DECIMAL(15,2),
    DISBURSED_AMOUNT DECIMAL(15,2),
    OUTSTANDING_PRINCIPAL DECIMAL(15,2),
    OUTSTANDING_INTEREST DECIMAL(15,2),
    TOTAL_OUTSTANDING DECIMAL(15,2),
    OVERDUE_PRINCIPAL DECIMAL(15,2) DEFAULT 0.00,
    OVERDUE_INTEREST DECIMAL(15,2) DEFAULT 0.00,
    PENALTY_AMOUNT DECIMAL(13,2) DEFAULT 0.00,
    INTEREST_RATE DECIMAL(6,4),
    INTEREST_TYPE CHAR(1) CHECK (INTEREST_TYPE IN ('F', 'V')),
    LOAN_TERM_MONTHS INTEGER,
    PAYMENT_FREQUENCY CHAR(1) CHECK (PAYMENT_FREQUENCY IN ('M', 'Q', 'A')),
    INSTALLMENT_AMOUNT DECIMAL(13,2),
    BALLOON_PAYMENT DECIMAL(15,2),
    APPLICATION_DATE DATE,
    APPROVAL_DATE DATE,
    DISBURSEMENT_DATE DATE,
    FIRST_PAYMENT_DATE DATE,
    NEXT_PAYMENT_DATE DATE,
    LAST_PAYMENT_DATE DATE,
    MATURITY_DATE DATE,
    LAST_INTEREST_DATE DATE,
    TOTAL_PAYMENTS_MADE INTEGER DEFAULT 0,
    PAYMENTS_REMAINING INTEGER,
    LAST_PAYMENT_AMOUNT DECIMAL(13,2),
    TOTAL_PAID_PRINCIPAL DECIMAL(15,2) DEFAULT 0.00,
    TOTAL_PAID_INTEREST DECIMAL(15,2) DEFAULT 0.00,
    DAYS_PAST_DUE INTEGER DEFAULT 0,
    DELINQUENCY_STATUS CHAR(1) CHECK (DELINQUENCY_STATUS IN ('C', '1', '2', '3', '4')),
    COLLATERAL_TYPE VARCHAR(3),
    COLLATERAL_VALUE DECIMAL(15,2),
    LTV_RATIO DECIMAL(5,2),
    COLLATERAL_DESCRIPTION VARCHAR(100),
    LOAN_OFFICER_ID VARCHAR(8),
    APPROVER_ID VARCHAR(8),
    BRANCH_CODE INTEGER,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- ============================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================
CREATE INDEX IDX_CUSTOMER_STATUS ON CUSTOMER(CUSTOMER_STATUS);
CREATE INDEX IDX_CUSTOMER_SEGMENT ON CUSTOMER(CUSTOMER_SEGMENT);
CREATE INDEX IDX_ACCOUNT_CUSTOMER ON ACCOUNT(CUSTOMER_ID);
CREATE INDEX IDX_ACCOUNT_STATUS ON ACCOUNT(ACCOUNT_STATUS);
CREATE INDEX IDX_ACCOUNT_TYPE ON ACCOUNT(ACCOUNT_TYPE);
CREATE INDEX IDX_TRANSACTION_DATE ON TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IDX_TRANSACTION_FROM ON TRANSACTION(FROM_ACCOUNT);
CREATE INDEX IDX_TRANSACTION_TO ON TRANSACTION(TO_ACCOUNT);
CREATE INDEX IDX_TRANSACTION_TYPE ON TRANSACTION(TRANSACTION_TYPE);
CREATE INDEX IDX_LOAN_CUSTOMER ON LOAN(CUSTOMER_ID);
CREATE INDEX IDX_LOAN_STATUS ON LOAN(LOAN_STATUS);

COMMIT;

-- Made with Bob
